### PR TITLE
New app wiki

### PR DESCRIPTION
**Pull request by zeelyha**

### CODE REVIEW

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Comment by zeelyha** [comment]
#34

**Review by adilimudassir — APPROVED** [review]

**Comment by adilimudassir** [comment]
Thank you Zeelyha

**Comment by zeelyha** [comment]
Thank you too. I am open to work on more tasks.

**Comment by adilimudassir** [comment]
Sure 👍

**Pull request merged**
